import {
  Add,
  Menu,
  More,
  MoreHoriz,
  MoreVert,
  Search,
} from "@mui/icons-material";
import {
  AppBar,
  Avatar,
  Box,
  Fab,
  IconButton,
  List,
  ListItemAvatar,
  ListItemButton,
  ListItemText,
  ListSubheader,
  Paper,
  Stack,
  Toolbar,
  Typography,
} from "@mui/material";
import React from "react";

const messages = [
  {
    id: 1,
    primary: "Brunch this week?",
    secondary:
      "I'll be in the neighbourhood this week. Let's grab a bite to eat",
    person: "/static/images/avatar/5.jpg",
  },
  {
    id: 2,
    primary: "Birthday Gift",
    secondary: `Do you have a suggestion for a good present for John on his work
      anniversary. I am really confused & would love your thoughts on it.`,
    person: "/static/images/avatar/1.jpg",
  },
  {
    id: 3,
    primary: "Recipe to try",
    secondary:
      "I am try out this new BBQ recipe, I think this might be amazing",
    person: "/static/images/avatar/2.jpg",
  },
  {
    id: 4,
    primary: "Yes!",
    secondary: "I have the tickets to the ReactConf for this year.",
    person: "/static/images/avatar/3.jpg",
  },
  {
    id: 5,
    primary: "Doctor's Appointment",
    secondary:
      "My appointment for the doctor was rescheduled for next Saturday.",
    person: "/static/images/avatar/4.jpg",
  },
  {
    id: 6,
    primary: "Discussion",
    secondary: `Menus that are generated by the bottom app bar (such as a bottom
      navigation drawer or overflow menu) open as bottom sheets at a higher elevation
      than the bar.`,
    person: "/static/images/avatar/5.jpg",
  },
  {
    id: 7,
    primary: "Summer BBQ",
    secondary: `Who wants to have a cookout this weekend? I just got some furniture
      for my backyard and would love to fire up the grill.`,
    person: "/static/images/avatar/1.jpg",
  },
];

const BottomAppBar = () => {
  return (
    <Stack justifyContent={"center"} alignItems={"center"}>
      <Box
        sx={{
          flexGrow: 1,
          display: "flex",
          width: "100%",
          position: "relative",
        }}
      >
        <Paper
          square
          sx={{
            pb: "50px",
            width: "100%",
          }}
        >
          <Typography
            variant="h5"
            gutterBottom
            component={"div"}
            sx={{ p: 2, pb: 0 }}
          >
            Inbox
          </Typography>
          <List sx={{ mb: 2 }}>
            {messages.map(({ id, primary, secondary, person }) => (
              <React.Fragment key={id}>
                {id === 1 && (
                  <ListSubheader sx={{ bgcolor: "background.paper" }}>
                    Today
                  </ListSubheader>
                )}
                {id === 3 && (
                  <ListSubheader sx={{ bgcolor: "background.paper" }}>
                    Yesterday
                  </ListSubheader>
                )}
                <ListItemButton>
                  <ListItemAvatar>
                    <Avatar alt="Profile Picture" src={person} />
                  </ListItemAvatar>
                  <ListItemText primary={primary} secondary={secondary} />
                </ListItemButton>
              </React.Fragment>
            ))}
          </List>
        </Paper>
        <AppBar
          position="fixed"
          color="primary"
          sx={{ top: "auto", bottom: 0 }}
        >
          <Toolbar>
            <IconButton color="inherit" aria-label="open drawer">
              <Menu />
            </IconButton>
            <Fab
              color="secondary"
              aria-label="add"
              sx={{
                position: "absolute",
                left: "50%",
                top: 0,
                transform: `translate(-50%, -50%)`,
              }}
            >
              <Add />
            </Fab>
            <Box sx={{ flexGrow: 1 }} />
            <IconButton color="inherit">
              <Search />
            </IconButton>
            <IconButton color="inherit">
              <MoreVert />
            </IconButton>
          </Toolbar>
        </AppBar>
      </Box>
    </Stack>
  );
};

export default BottomAppBar;
